const scrapedVocabulary = [
  'artistsA',
  'artistsBPtOne',
  'artistsBPtTwo',
  'artistsBPtThree',
  'artistsV',
  'artistsG',
  'artistsD',
  'artistsE',
  'artistsZhe',
  'artistsZ',
  'artistsI',
  'artistsJi',
  'artistsK',
  'artistsL',
  'artistsM',
  'artistsN',
  'artistsO',
  'artistsP',
  'artistsR',
  'artistsS',
  'artistsT',
  'artistsU',
  'artistsF',
  'artistsH',
  'artistsCe',
  'artistsChe',
  'artistsSh',
  'artistsSsch',
  'artistsAE',
  'artistsYu',
  'artistsYa',
]


export default scrapedVocabulary
